# Generated by Django 4.1.2 on 2022-10-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_delete_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Professor',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='nome',
            new_name='name',
        ),
    ]
