# Generated by Django 4.1.2 on 2022-10-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_rename_name_professor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField()),
                ('photo', models.URLField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
